// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import AppointmentBookingController from "./appointment_booking_controller";
application.register("appointment-booking", AppointmentBookingController);
